REM DATA LOADING SCRIPT

REM SETTING ENVIRONMENT PARAMETERS
SET ENVIRONMENT=%1
SET MONGO_HOST=%2
SET MONGO_DB=%3
SET MONGO_USER=%4
SET MONGO_PASSWORD=%5
SET MONGODB_ATLAS_CLUSTER_URI=mongodb+srv://%MONGO_USER%:%MONGO_PASSWORD%@%MONGO_HOST%/%MONGO_DB%

REM RUN DATALOADING SCRIPTS
node dataload.js
